### ISSUE TITLE
feature: Need doc on git tagging and release procedure

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/ocm-status-addon#10]
### Feature Description

Contributors need to be told how to make a new release, including what are the git tags involved.

### Proposed Solution

Document it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@pdettori

**Comment by pdettori** [comment]
This has been addressed by https://github.com/kubestellar/ocm-status-addon/pull/16
