### ISSUE TITLE
feature: Add e2e test

### ISSUE THREAD

**Issue by waltforme** [kubestellar/ocm-status-addon#26]
### Feature Description

I was doing test manually when working on the API group change for WorkStatus. Looks like it is a good time to automate the test.

### Proposed Solution

We can do something similar to KS/KS using shell scripts, but we'd better **not** to introduce dependencies on KS/KS in the scripts.

**Comment by ezrasilvera** [comment]
@waltforme is it a test in this repo, or in ks repo that uses the addon?

**Comment by waltforme** [comment]
It is test in this repo, against changes to this repo. @ezrasilvera

**Comment by pdettori** [comment]
@waltforme is this work complete? can we close this issue?

**Comment by pdettori** [comment]
@waltforme yes, definitely. We could test with for a number of objects removal and recreation, and testing if the number of work status at the end is what expected. This is pretty much the scenario I used to replicate issues seen in https://github.com/kubestellar/kubestellar/issues/1820 - note just creating 10 objects, deleting and re-creating was enough to surface some issues in the code.

**Comment by waltforme** [comment]
I see. I'll work on this right after current work on CRD handling merged. Thanks!
