### ISSUE TITLE
feature: Missing Named Ports and Labels for Prometheus and Pyroscope scraping

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/ocm-status-addon#81]
### Feature Description

To conduct our KS performance tests, we need named ports and appropriate labels for prometheus and pyroscope scraping for both status-addon-controller and status-agent-controller. 

### Proposed Solution

Add in the status-addon-controller and status-agent-controller the respective ports and appropriate labels need for prometheus and pyroscope scraping 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
addressed by #83
